// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/kasuboski/mediaz/pkg/indexer (interfaces: IndexerSource,Factory)
//
// Generated by this command:
//
//	mockgen -destination=mocks/mock_indexer_source.go -package=mocks github.com/kasuboski/mediaz/pkg/indexer IndexerSource,Factory
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	indexer "github.com/kasuboski/mediaz/pkg/indexer"
	prowlarr "github.com/kasuboski/mediaz/pkg/prowlarr"
	model "github.com/kasuboski/mediaz/pkg/storage/sqlite/schema/gen/model"
	gomock "go.uber.org/mock/gomock"
)

// MockIndexerSource is a mock of IndexerSource interface.
type MockIndexerSource struct {
	ctrl     *gomock.Controller
	recorder *MockIndexerSourceMockRecorder
}

// MockIndexerSourceMockRecorder is the mock recorder for MockIndexerSource.
type MockIndexerSourceMockRecorder struct {
	mock *MockIndexerSource
}

// NewMockIndexerSource creates a new mock instance.
func NewMockIndexerSource(ctrl *gomock.Controller) *MockIndexerSource {
	mock := &MockIndexerSource{ctrl: ctrl}
	mock.recorder = &MockIndexerSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockIndexerSource) EXPECT() *MockIndexerSourceMockRecorder {
	return m.recorder
}

// ListIndexers mocks base method.
func (m *MockIndexerSource) ListIndexers(arg0 context.Context) ([]indexer.SourceIndexer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListIndexers", arg0)
	ret0, _ := ret[0].([]indexer.SourceIndexer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListIndexers indicates an expected call of ListIndexers.
func (mr *MockIndexerSourceMockRecorder) ListIndexers(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListIndexers", reflect.TypeOf((*MockIndexerSource)(nil).ListIndexers), arg0)
}

// Search mocks base method.
func (m *MockIndexerSource) Search(arg0 context.Context, arg1 int32, arg2 []int32, arg3 string) ([]*prowlarr.ReleaseResource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Search", arg0, arg1, arg2, arg3)
	ret0, _ := ret[0].([]*prowlarr.ReleaseResource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Search indicates an expected call of Search.
func (mr *MockIndexerSourceMockRecorder) Search(arg0, arg1, arg2, arg3 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Search", reflect.TypeOf((*MockIndexerSource)(nil).Search), arg0, arg1, arg2, arg3)
}

// MockFactory is a mock of Factory interface.
type MockFactory struct {
	ctrl     *gomock.Controller
	recorder *MockFactoryMockRecorder
}

// MockFactoryMockRecorder is the mock recorder for MockFactory.
type MockFactoryMockRecorder struct {
	mock *MockFactory
}

// NewMockFactory creates a new mock instance.
func NewMockFactory(ctrl *gomock.Controller) *MockFactory {
	mock := &MockFactory{ctrl: ctrl}
	mock.recorder = &MockFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockFactory) EXPECT() *MockFactoryMockRecorder {
	return m.recorder
}

// NewIndexerSource mocks base method.
func (m *MockFactory) NewIndexerSource(arg0 model.IndexerSource) (indexer.IndexerSource, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NewIndexerSource", arg0)
	ret0, _ := ret[0].(indexer.IndexerSource)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// NewIndexerSource indicates an expected call of NewIndexerSource.
func (mr *MockFactoryMockRecorder) NewIndexerSource(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NewIndexerSource", reflect.TypeOf((*MockFactory)(nil).NewIndexerSource), arg0)
}
