{{- if .Values.httproute.enabled -}}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "mediaz.fullname" . }}
  {{- with .Values.httproute.namespace }}
  namespace: {{ . }}
  {{- end }}
  labels:
    {{- include "mediaz.labels" . | nindent 4 }}
    {{- with .Values.httproute.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- with .Values.httproute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  {{- with .Values.httproute.parentRefs }}
  parentRefs:
    {{- range . }}
    - name: {{ .name }}
      {{- with .namespace }}
      namespace: {{ . }}
      {{- end }}
      {{- with .sectionName }}
      sectionName: {{ . }}
      {{- end }}
      {{- with .port }}
      port: {{ . }}
      {{- end }}
      {{- with .group }}
      group: {{ . }}
      {{- end }}
      {{- with .kind }}
      kind: {{ . }}
      {{- end }}
    {{- end }}
  {{- end }}
  {{- with .Values.httproute.hostnames }}
  hostnames:
    {{- range . }}
    - {{ . | quote }}
    {{- end }}
  {{- end }}
  rules:
    {{- range .Values.httproute.rules }}
    - {{- with .matches }}
      matches:
        {{- range . }}
        - {{- with .path }}
          path:
            type: {{ .type | default "PathPrefix" }}
            value: {{ .value | quote }}
          {{- end }}
          {{- with .headers }}
          headers:
            {{- range . }}
            - name: {{ .name | quote }}
              type: {{ .type | default "Exact" }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- with .queryParams }}
          queryParams:
            {{- range . }}
            - name: {{ .name | quote }}
              type: {{ .type | default "Exact" }}
              value: {{ .value | quote }}
            {{- end }}
          {{- end }}
          {{- with .method }}
          method: {{ . | quote }}
          {{- end }}
        {{- end }}
      {{- end }}
      {{- with .filters }}
      filters:
        {{- range . }}
        - type: {{ .type }}
          {{- if eq .type "RequestHeaderModifier" }}
          {{- with .requestHeaderModifier }}
          requestHeaderModifier:
            {{- with .set }}
            set:
              {{- range . }}
              - name: {{ .name | quote }}
                value: {{ .value | quote }}
              {{- end }}
            {{- end }}
            {{- with .add }}
            add:
              {{- range . }}
              - name: {{ .name | quote }}
                value: {{ .value | quote }}
              {{- end }}
            {{- end }}
            {{- with .remove }}
            remove:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if eq .type "ResponseHeaderModifier" }}
          {{- with .responseHeaderModifier }}
          responseHeaderModifier:
            {{- with .set }}
            set:
              {{- range . }}
              - name: {{ .name | quote }}
                value: {{ .value | quote }}
              {{- end }}
            {{- end }}
            {{- with .add }}
            add:
              {{- range . }}
              - name: {{ .name | quote }}
                value: {{ .value | quote }}
              {{- end }}
            {{- end }}
            {{- with .remove }}
            remove:
              {{- toYaml . | nindent 14 }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if eq .type "RequestRedirect" }}
          {{- with .requestRedirect }}
          requestRedirect:
            {{- with .scheme }}
            scheme: {{ . | quote }}
            {{- end }}
            {{- with .hostname }}
            hostname: {{ . | quote }}
            {{- end }}
            {{- with .path }}
            path:
              type: {{ .type }}
              {{- with .replaceFullPath }}
              replaceFullPath: {{ . | quote }}
              {{- end }}
              {{- with .replacePrefixMatch }}
              replacePrefixMatch: {{ . | quote }}
              {{- end }}
            {{- end }}
            {{- with .port }}
            port: {{ . }}
            {{- end }}
            {{- with .statusCode }}
            statusCode: {{ . }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if eq .type "URLRewrite" }}
          {{- with .urlRewrite }}
          urlRewrite:
            {{- with .hostname }}
            hostname: {{ . | quote }}
            {{- end }}
            {{- with .path }}
            path:
              type: {{ .type }}
              {{- with .replaceFullPath }}
              replaceFullPath: {{ . | quote }}
              {{- end }}
              {{- with .replacePrefixMatch }}
              replacePrefixMatch: {{ . | quote }}
              {{- end }}
            {{- end }}
          {{- end }}
          {{- end }}
          {{- if eq .type "RequestMirror" }}
          {{- with .requestMirror }}
          requestMirror:
            backendRef:
              name: {{ .backendRef.name }}
              {{- with .backendRef.namespace }}
              namespace: {{ . }}
              {{- end }}
              {{- with .backendRef.port }}
              port: {{ . }}
              {{- end }}
              {{- with .backendRef.group }}
              group: {{ . }}
              {{- end }}
              {{- with .backendRef.kind }}
              kind: {{ . }}
              {{- end }}
              {{- with .backendRef.weight }}
              weight: {{ . }}
              {{- end }}
          {{- end }}
          {{- end }}
          {{- if eq .type "ExtensionRef" }}
          {{- with .extensionRef }}
          extensionRef:
            group: {{ .group }}
            kind: {{ .kind }}
            name: {{ .name }}
          {{- end }}
          {{- end }}
        {{- end }}
      {{- end }}
      backendRefs:
        {{- range .backendRefs }}
        - name: {{ .name | default (include "mediaz.fullname" $) }}
          {{- with .namespace }}
          namespace: {{ . }}
          {{- end }}
          port: {{ .port | default $.Values.service.port }}
          {{- with .group }}
          group: {{ . }}
          {{- end }}
          {{- with .kind }}
          kind: {{ . }}
          {{- end }}
          {{- with .weight }}
          weight: {{ . }}
          {{- end }}
          {{- with .filters }}
          filters:
            {{- range . }}
            - type: {{ .type }}
              {{- if eq .type "RequestHeaderModifier" }}
              {{- with .requestHeaderModifier }}
              requestHeaderModifier:
                {{- with .set }}
                set:
                  {{- range . }}
                  - name: {{ .name | quote }}
                    value: {{ .value | quote }}
                  {{- end }}
                {{- end }}
                {{- with .add }}
                add:
                  {{- range . }}
                  - name: {{ .name | quote }}
                    value: {{ .value | quote }}
                  {{- end }}
                {{- end }}
                {{- with .remove }}
                remove:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
              {{- end }}
              {{- end }}
              {{- if eq .type "ResponseHeaderModifier" }}
              {{- with .responseHeaderModifier }}
              responseHeaderModifier:
                {{- with .set }}
                set:
                  {{- range . }}
                  - name: {{ .name | quote }}
                    value: {{ .value | quote }}
                  {{- end }}
                {{- end }}
                {{- with .add }}
                add:
                  {{- range . }}
                  - name: {{ .name | quote }}
                    value: {{ .value | quote }}
                  {{- end }}
                {{- end }}
                {{- with .remove }}
                remove:
                  {{- toYaml . | nindent 18 }}
                {{- end }}
              {{- end }}
              {{- end }}
              {{- if eq .type "RequestRedirect" }}
              {{- with .requestRedirect }}
              requestRedirect:
                {{- with .scheme }}
                scheme: {{ . | quote }}
                {{- end }}
                {{- with .hostname }}
                hostname: {{ . | quote }}
                {{- end }}
                {{- with .path }}
                path:
                  type: {{ .type }}
                  {{- with .replaceFullPath }}
                  replaceFullPath: {{ . | quote }}
                  {{- end }}
                  {{- with .replacePrefixMatch }}
                  replacePrefixMatch: {{ . | quote }}
                  {{- end }}
                {{- end }}
                {{- with .port }}
                port: {{ . }}
                {{- end }}
                {{- with .statusCode }}
                statusCode: {{ . }}
                {{- end }}
              {{- end }}
              {{- end }}
              {{- if eq .type "URLRewrite" }}
              {{- with .urlRewrite }}
              urlRewrite:
                {{- with .hostname }}
                hostname: {{ . | quote }}
                {{- end }}
                {{- with .path }}
                path:
                  type: {{ .type }}
                  {{- with .replaceFullPath }}
                  replaceFullPath: {{ . | quote }}
                  {{- end }}
                  {{- with .replacePrefixMatch }}
                  replacePrefixMatch: {{ . | quote }}
                  {{- end }}
                {{- end }}
              {{- end }}
              {{- end }}
              {{- if eq .type "RequestMirror" }}
              {{- with .requestMirror }}
              requestMirror:
                backendRef:
                  name: {{ .backendRef.name }}
                  {{- with .backendRef.namespace }}
                  namespace: {{ . }}
                  {{- end }}
                  {{- with .backendRef.port }}
                  port: {{ . }}
                  {{- end }}
                  {{- with .backendRef.group }}
                  group: {{ . }}
                  {{- end }}
                  {{- with .backendRef.kind }}
                  kind: {{ . }}
                  {{- end }}
                  {{- with .backendRef.weight }}
                  weight: {{ . }}
                  {{- end }}
              {{- end }}
              {{- end }}
              {{- if eq .type "ExtensionRef" }}
              {{- with .extensionRef }}
              extensionRef:
                group: {{ .group }}
                kind: {{ .kind }}
                name: {{ .name }}
              {{- end }}
              {{- end }}
            {{- end }}
          {{- end }}
        {{- end }}
      {{- with .timeouts }}
      timeouts:
        {{- with .request }}
        request: {{ . }}
        {{- end }}
        {{- with .backendRequest }}
        backendRequest: {{ . }}
        {{- end }}
      {{- end }}
    {{- end }}
{{- end }}