//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package model

import (
	"time"
)

type Movies struct {
	ID                  int32 `sql:"primary_key"`
	Path                string
	Monitored           int32
	QualityProfileId    int32
	Added               *time.Time
	Tags                *string
	AddOptions          *string
	MovieFileId         int32
	MinimumAvailability int32
	MovieMetadataId     int32
	LastSearchTime      *time.Time
}
