// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activity.sql

package sqlcdb

import (
	"context"
	"database/sql"
)

const countTransitionsByDate = `-- name: CountTransitionsByDate :one
SELECT (
    SELECT COUNT(*) FROM movie_transition AS mt
    INNER JOIN movie AS m ON mt.movie_id = m.id
    WHERE
        mt.created_at >= DATETIME(?) AND mt.created_at <= DATETIME(?)
        AND mt.most_recent = 1
) + (
    SELECT COUNT(*) FROM season_transition AS st
    INNER JOIN season AS s ON st.season_id = s.id
    WHERE
        st.created_at >= DATETIME(?) AND st.created_at <= DATETIME(?)
        AND st.most_recent = 1
) + (
    SELECT COUNT(*) FROM episode_transition AS et
    INNER JOIN episode AS e ON et.episode_id = e.id
    WHERE
        et.created_at >= DATETIME(?) AND et.created_at <= DATETIME(?)
        AND et.most_recent = 1
) + (
    SELECT COUNT(*) FROM job_transition AS jt
    INNER JOIN job AS j ON jt.job_id = j.id
    WHERE
        jt.created_at >= DATETIME(?) AND jt.created_at <= DATETIME(?)
        AND jt.most_recent = 1
) AS total
`

type CountTransitionsByDateParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
	Datetime_3 interface{}
	Datetime_4 interface{}
	Datetime_5 interface{}
	Datetime_6 interface{}
	Datetime_7 interface{}
	Datetime_8 interface{}
}

func (q *Queries) CountTransitionsByDate(ctx context.Context, arg CountTransitionsByDateParams) (int64, error) {
	row := q.db.QueryRowContext(ctx, countTransitionsByDate,
		arg.Datetime,
		arg.Datetime_2,
		arg.Datetime_3,
		arg.Datetime_4,
		arg.Datetime_5,
		arg.Datetime_6,
		arg.Datetime_7,
		arg.Datetime_8,
	)
	var total int64
	err := row.Scan(&total)
	return total, err
}

const getEntityTransitionsEpisode = `-- name: GetEntityTransitionsEpisode :many
SELECT
    sm.title AS entity_title,
    sm.poster_path,
    et.to_state,
    et.from_state,
    et.created_at,
    et.sort_key
FROM episode AS e
INNER JOIN episode_transition AS et ON e.id = et.episode_id
INNER JOIN season AS s ON e.season_id = s.id
INNER JOIN series AS ser ON s.series_id = ser.id
LEFT JOIN series_metadata AS sm ON ser.series_metadata_id = sm.id
WHERE e.id = ?
ORDER BY et.sort_key ASC
`

type GetEntityTransitionsEpisodeRow struct {
	EntityTitle sql.NullString
	PosterPath  sql.NullString
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	SortKey     int64
}

func (q *Queries) GetEntityTransitionsEpisode(ctx context.Context, id int64) ([]GetEntityTransitionsEpisodeRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntityTransitionsEpisode, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityTransitionsEpisodeRow
	for rows.Next() {
		var i GetEntityTransitionsEpisodeRow
		if err := rows.Scan(
			&i.EntityTitle,
			&i.PosterPath,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityTransitionsJob = `-- name: GetEntityTransitionsJob :many
SELECT
    j.type AS entity_title,
    '' AS poster_path,
    jt.to_state,
    jt.from_state,
    jt.created_at,
    jt.sort_key
FROM job AS j
INNER JOIN job_transition AS jt ON j.id = jt.job_id
WHERE j.id = ?
ORDER BY jt.sort_key ASC
`

type GetEntityTransitionsJobRow struct {
	EntityTitle string
	PosterPath  string
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	SortKey     int64
}

func (q *Queries) GetEntityTransitionsJob(ctx context.Context, id int64) ([]GetEntityTransitionsJobRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntityTransitionsJob, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityTransitionsJobRow
	for rows.Next() {
		var i GetEntityTransitionsJobRow
		if err := rows.Scan(
			&i.EntityTitle,
			&i.PosterPath,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityTransitionsMovie = `-- name: GetEntityTransitionsMovie :many
SELECT
    mm.title AS entity_title,
    mm.images AS poster_path,
    mt.to_state,
    mt.from_state,
    mt.created_at,
    mt.sort_key,
    CAST(JSON_OBJECT(
        'downloadClient',
        JSON_OBJECT('id', dc.id, 'host', dc.host, 'port', dc.port),
        'downloadID', mt.download_id
    ) AS TEXT) AS metadata
FROM movie AS m
INNER JOIN movie_transition AS mt ON m.id = mt.movie_id
LEFT JOIN movie_metadata AS mm ON m.movie_metadata_id = mm.id
LEFT JOIN download_client AS dc ON mt.download_client_id = dc.id
WHERE m.id = ?
ORDER BY mt.sort_key ASC
`

type GetEntityTransitionsMovieRow struct {
	EntityTitle sql.NullString
	PosterPath  sql.NullString
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	SortKey     int64
	Metadata    string
}

func (q *Queries) GetEntityTransitionsMovie(ctx context.Context, id int64) ([]GetEntityTransitionsMovieRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntityTransitionsMovie, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityTransitionsMovieRow
	for rows.Next() {
		var i GetEntityTransitionsMovieRow
		if err := rows.Scan(
			&i.EntityTitle,
			&i.PosterPath,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.SortKey,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityTransitionsSeason = `-- name: GetEntityTransitionsSeason :many
SELECT
    sm.title AS entity_title,
    sm.poster_path,
    st.to_state,
    st.from_state,
    st.created_at,
    st.sort_key,
    CAST(JSON_OBJECT(
        'downloadClient',
        JSON_OBJECT('id', dc.id, 'host', dc.host, 'port', dc.port),
        'downloadID', st.download_id
    ) AS TEXT) AS metadata
FROM season AS s
INNER JOIN season_transition AS st ON s.id = st.season_id
INNER JOIN series AS ser ON s.series_id = ser.id
LEFT JOIN series_metadata AS sm ON ser.series_metadata_id = sm.id
LEFT JOIN download_client AS dc ON st.download_client_id = dc.id
WHERE s.id = ?
ORDER BY st.sort_key ASC
`

type GetEntityTransitionsSeasonRow struct {
	EntityTitle sql.NullString
	PosterPath  sql.NullString
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	SortKey     int64
	Metadata    string
}

func (q *Queries) GetEntityTransitionsSeason(ctx context.Context, id int64) ([]GetEntityTransitionsSeasonRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntityTransitionsSeason, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityTransitionsSeasonRow
	for rows.Next() {
		var i GetEntityTransitionsSeasonRow
		if err := rows.Scan(
			&i.EntityTitle,
			&i.PosterPath,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.SortKey,
			&i.Metadata,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEntityTransitionsSeries = `-- name: GetEntityTransitionsSeries :many
SELECT
    sm.title AS entity_title,
    sm.poster_path,
    st.to_state,
    st.from_state,
    st.created_at,
    st.sort_key
FROM series AS s
INNER JOIN series_transition AS st ON s.id = st.series_id
LEFT JOIN series_metadata AS sm ON s.series_metadata_id = sm.id
WHERE s.id = ?
ORDER BY st.sort_key ASC
`

type GetEntityTransitionsSeriesRow struct {
	EntityTitle sql.NullString
	PosterPath  sql.NullString
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	SortKey     int64
}

func (q *Queries) GetEntityTransitionsSeries(ctx context.Context, id int64) ([]GetEntityTransitionsSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, getEntityTransitionsSeries, id)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityTransitionsSeriesRow
	for rows.Next() {
		var i GetEntityTransitionsSeriesRow
		if err := rows.Scan(
			&i.EntityTitle,
			&i.PosterPath,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.SortKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodeTransitionItems = `-- name: GetEpisodeTransitionItems :many
SELECT
    et.id,
    'episode' AS entity_type,
    e.id AS entity_id,
    et.to_state,
    et.from_state,
    et.created_at,
    COALESCE(sm.title, '') AS entity_title
FROM episode AS e
INNER JOIN episode_transition AS et ON e.id = et.episode_id
INNER JOIN season AS s ON e.season_id = s.id
INNER JOIN series AS ser ON s.series_id = ser.id
LEFT JOIN series_metadata AS sm ON ser.series_metadata_id = sm.id
WHERE
    et.created_at >= DATETIME(?)
    AND et.created_at <= DATETIME(?)
    AND et.most_recent = 1
ORDER BY et.created_at DESC
LIMIT ? OFFSET ?
`

type GetEpisodeTransitionItemsParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
	Limit      int64
	Offset     int64
}

type GetEpisodeTransitionItemsRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	EntityTitle string
}

func (q *Queries) GetEpisodeTransitionItems(ctx context.Context, arg GetEpisodeTransitionItemsParams) ([]GetEpisodeTransitionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodeTransitionItems,
		arg.Datetime,
		arg.Datetime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodeTransitionItemsRow
	for rows.Next() {
		var i GetEpisodeTransitionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.EntityTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getEpisodeTransitionItemsNoLimit = `-- name: GetEpisodeTransitionItemsNoLimit :many
SELECT
    et.id,
    'episode' AS entity_type,
    e.id AS entity_id,
    et.to_state,
    et.from_state,
    et.created_at,
    COALESCE(sm.title, '') AS entity_title
FROM episode AS e
INNER JOIN episode_transition AS et ON e.id = et.episode_id
INNER JOIN season AS s ON e.season_id = s.id
INNER JOIN series AS ser ON s.series_id = ser.id
LEFT JOIN series_metadata AS sm ON ser.series_metadata_id = sm.id
WHERE
    et.created_at >= DATETIME(?)
    AND et.created_at <= DATETIME(?)
    AND et.most_recent = 1
ORDER BY et.created_at DESC
`

type GetEpisodeTransitionItemsNoLimitParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
}

type GetEpisodeTransitionItemsNoLimitRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	EntityTitle string
}

func (q *Queries) GetEpisodeTransitionItemsNoLimit(ctx context.Context, arg GetEpisodeTransitionItemsNoLimitParams) ([]GetEpisodeTransitionItemsNoLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, getEpisodeTransitionItemsNoLimit, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEpisodeTransitionItemsNoLimitRow
	for rows.Next() {
		var i GetEpisodeTransitionItemsNoLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.EntityTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTransitionItems = `-- name: GetJobTransitionItems :many
SELECT
    jt.id,
    'job' AS entity_type,
    j.id AS entity_id,
    j.type AS entity_title,
    jt.to_state,
    jt.from_state,
    jt.created_at
FROM job AS j
INNER JOIN job_transition AS jt ON j.id = jt.job_id
WHERE
    jt.created_at >= DATETIME(?)
    AND jt.created_at <= DATETIME(?)
    AND jt.most_recent = 1
ORDER BY jt.created_at DESC
LIMIT ? OFFSET ?
`

type GetJobTransitionItemsParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
	Limit      int64
	Offset     int64
}

type GetJobTransitionItemsRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	EntityTitle string
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
}

func (q *Queries) GetJobTransitionItems(ctx context.Context, arg GetJobTransitionItemsParams) ([]GetJobTransitionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobTransitionItems,
		arg.Datetime,
		arg.Datetime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobTransitionItemsRow
	for rows.Next() {
		var i GetJobTransitionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.EntityTitle,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTransitionItemsNoLimit = `-- name: GetJobTransitionItemsNoLimit :many
SELECT
    jt.id,
    'job' AS entity_type,
    j.id AS entity_id,
    j.type AS entity_title,
    jt.to_state,
    jt.from_state,
    jt.created_at
FROM job AS j
INNER JOIN job_transition AS jt ON j.id = jt.job_id
WHERE
    jt.created_at >= DATETIME(?)
    AND jt.created_at <= DATETIME(?)
    AND jt.most_recent = 1
ORDER BY jt.created_at DESC
`

type GetJobTransitionItemsNoLimitParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
}

type GetJobTransitionItemsNoLimitRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	EntityTitle string
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
}

func (q *Queries) GetJobTransitionItemsNoLimit(ctx context.Context, arg GetJobTransitionItemsNoLimitParams) ([]GetJobTransitionItemsNoLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobTransitionItemsNoLimit, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobTransitionItemsNoLimitRow
	for rows.Next() {
		var i GetJobTransitionItemsNoLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.EntityTitle,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getJobTransitionsByDate = `-- name: GetJobTransitionsByDate :many
SELECT
    CAST(STRFTIME('%Y-%m-%d', jt.created_at) AS TEXT) AS date,
    COUNT(DISTINCT CASE WHEN jt.to_state = 'done' THEN j.id END) AS done,
    COUNT(DISTINCT CASE WHEN jt.to_state = 'error' THEN j.id END) AS error
FROM job AS j
INNER JOIN job_transition AS jt ON j.id = jt.job_id
WHERE
    jt.created_at >= DATETIME(?)
    AND jt.created_at <= DATETIME(?)
    AND jt.most_recent = 1
GROUP BY STRFTIME('%Y-%m-%d', jt.created_at)
ORDER BY date
`

type GetJobTransitionsByDateParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
}

type GetJobTransitionsByDateRow struct {
	Date  string
	Done  int64
	Error int64
}

func (q *Queries) GetJobTransitionsByDate(ctx context.Context, arg GetJobTransitionsByDateParams) ([]GetJobTransitionsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getJobTransitionsByDate, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetJobTransitionsByDateRow
	for rows.Next() {
		var i GetJobTransitionsByDateRow
		if err := rows.Scan(&i.Date, &i.Done, &i.Error); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieTransitionItems = `-- name: GetMovieTransitionItems :many
SELECT
    mt.id,
    'movie' AS entity_type,
    m.id AS entity_id,
    mt.to_state,
    mt.from_state,
    mt.created_at,
    COALESCE(mm.title, '') AS entity_title
FROM movie AS m
INNER JOIN movie_transition AS mt ON m.id = mt.movie_id
LEFT JOIN movie_metadata AS mm ON m.movie_metadata_id = mm.id
WHERE
    mt.created_at >= DATETIME(?)
    AND mt.created_at <= DATETIME(?)
    AND mt.most_recent = 1
ORDER BY mt.created_at DESC
LIMIT ? OFFSET ?
`

type GetMovieTransitionItemsParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
	Limit      int64
	Offset     int64
}

type GetMovieTransitionItemsRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	EntityTitle string
}

func (q *Queries) GetMovieTransitionItems(ctx context.Context, arg GetMovieTransitionItemsParams) ([]GetMovieTransitionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getMovieTransitionItems,
		arg.Datetime,
		arg.Datetime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieTransitionItemsRow
	for rows.Next() {
		var i GetMovieTransitionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.EntityTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieTransitionItemsNoLimit = `-- name: GetMovieTransitionItemsNoLimit :many
SELECT
    mt.id,
    'movie' AS entity_type,
    m.id AS entity_id,
    mt.to_state,
    mt.from_state,
    mt.created_at,
    COALESCE(mm.title, '') AS entity_title
FROM movie AS m
INNER JOIN movie_transition AS mt ON m.id = mt.movie_id
LEFT JOIN movie_metadata AS mm ON m.movie_metadata_id = mm.id
WHERE
    mt.created_at >= DATETIME(?)
    AND mt.created_at <= DATETIME(?)
    AND mt.most_recent = 1
ORDER BY mt.created_at DESC
`

type GetMovieTransitionItemsNoLimitParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
}

type GetMovieTransitionItemsNoLimitRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	EntityTitle string
}

func (q *Queries) GetMovieTransitionItemsNoLimit(ctx context.Context, arg GetMovieTransitionItemsNoLimitParams) ([]GetMovieTransitionItemsNoLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, getMovieTransitionItemsNoLimit, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieTransitionItemsNoLimitRow
	for rows.Next() {
		var i GetMovieTransitionItemsNoLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.EntityTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMovieTransitionsByDate = `-- name: GetMovieTransitionsByDate :many
SELECT
    CAST(STRFTIME('%Y-%m-%d', mt.created_at) AS TEXT) AS date,
    COUNT(DISTINCT CASE WHEN mt.to_state = 'downloaded' THEN m.id END)
        AS downloaded,
    COUNT(DISTINCT CASE WHEN mt.to_state = 'downloading' THEN m.id END)
        AS downloading
FROM movie AS m
INNER JOIN movie_transition AS mt ON m.id = mt.movie_id
WHERE
    mt.created_at >= DATETIME(?)
    AND mt.created_at <= DATETIME(?)
    AND mt.most_recent = 1
GROUP BY STRFTIME('%Y-%m-%d', mt.created_at)
ORDER BY date
`

type GetMovieTransitionsByDateParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
}

type GetMovieTransitionsByDateRow struct {
	Date        string
	Downloaded  int64
	Downloading int64
}

func (q *Queries) GetMovieTransitionsByDate(ctx context.Context, arg GetMovieTransitionsByDateParams) ([]GetMovieTransitionsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getMovieTransitionsByDate, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMovieTransitionsByDateRow
	for rows.Next() {
		var i GetMovieTransitionsByDateRow
		if err := rows.Scan(&i.Date, &i.Downloaded, &i.Downloading); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonTransitionItems = `-- name: GetSeasonTransitionItems :many
SELECT
    st.id,
    'season' AS entity_type,
    s.id AS entity_id,
    st.to_state,
    st.from_state,
    st.created_at,
    COALESCE(sm.title, '') AS entity_title
FROM season AS s
INNER JOIN season_transition AS st ON s.id = st.season_id
INNER JOIN series AS ser ON s.series_id = ser.id
LEFT JOIN series_metadata AS sm ON ser.series_metadata_id = sm.id
WHERE
    st.created_at >= DATETIME(?)
    AND st.created_at <= DATETIME(?)
    AND st.most_recent = 1
ORDER BY st.created_at DESC
LIMIT ? OFFSET ?
`

type GetSeasonTransitionItemsParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
	Limit      int64
	Offset     int64
}

type GetSeasonTransitionItemsRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	EntityTitle string
}

func (q *Queries) GetSeasonTransitionItems(ctx context.Context, arg GetSeasonTransitionItemsParams) ([]GetSeasonTransitionItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonTransitionItems,
		arg.Datetime,
		arg.Datetime_2,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonTransitionItemsRow
	for rows.Next() {
		var i GetSeasonTransitionItemsRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.EntityTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeasonTransitionItemsNoLimit = `-- name: GetSeasonTransitionItemsNoLimit :many
SELECT
    st.id,
    'season' AS entity_type,
    s.id AS entity_id,
    st.to_state,
    st.from_state,
    st.created_at,
    COALESCE(sm.title, '') AS entity_title
FROM season AS s
INNER JOIN season_transition AS st ON s.id = st.season_id
INNER JOIN series AS ser ON s.series_id = ser.id
LEFT JOIN series_metadata AS sm ON ser.series_metadata_id = sm.id
WHERE
    st.created_at >= DATETIME(?)
    AND st.created_at <= DATETIME(?)
    AND st.most_recent = 1
ORDER BY st.created_at DESC
`

type GetSeasonTransitionItemsNoLimitParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
}

type GetSeasonTransitionItemsNoLimitRow struct {
	ID          int64
	EntityType  string
	EntityID    int64
	ToState     string
	FromState   sql.NullString
	CreatedAt   sql.NullTime
	EntityTitle string
}

func (q *Queries) GetSeasonTransitionItemsNoLimit(ctx context.Context, arg GetSeasonTransitionItemsNoLimitParams) ([]GetSeasonTransitionItemsNoLimitRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeasonTransitionItemsNoLimit, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeasonTransitionItemsNoLimitRow
	for rows.Next() {
		var i GetSeasonTransitionItemsNoLimitRow
		if err := rows.Scan(
			&i.ID,
			&i.EntityType,
			&i.EntityID,
			&i.ToState,
			&i.FromState,
			&i.CreatedAt,
			&i.EntityTitle,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSeriesTransitionsByDate = `-- name: GetSeriesTransitionsByDate :many
SELECT
    CAST(STRFTIME('%Y-%m-%d', st.created_at) AS TEXT) AS date,
    COUNT(DISTINCT CASE WHEN st.to_state = 'completed' THEN ser.id END)
        AS completed,
    COUNT(DISTINCT CASE WHEN st.to_state = 'downloading' THEN ser.id END)
        AS downloading
FROM season AS s
INNER JOIN season_transition AS st ON s.id = st.season_id
INNER JOIN series AS ser ON s.series_id = ser.id
WHERE
    st.created_at >= DATETIME(?)
    AND st.created_at <= DATETIME(?)
    AND st.most_recent = 1
GROUP BY STRFTIME('%Y-%m-%d', st.created_at)
ORDER BY date
`

type GetSeriesTransitionsByDateParams struct {
	Datetime   interface{}
	Datetime_2 interface{}
}

type GetSeriesTransitionsByDateRow struct {
	Date        string
	Completed   int64
	Downloading int64
}

func (q *Queries) GetSeriesTransitionsByDate(ctx context.Context, arg GetSeriesTransitionsByDateParams) ([]GetSeriesTransitionsByDateRow, error) {
	rows, err := q.db.QueryContext(ctx, getSeriesTransitionsByDate, arg.Datetime, arg.Datetime_2)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSeriesTransitionsByDateRow
	for rows.Next() {
		var i GetSeriesTransitionsByDateRow
		if err := rows.Scan(&i.Date, &i.Completed, &i.Downloading); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadingMovies = `-- name: ListDownloadingMovies :many
SELECT
    m.id,
    mm.tmdb_id,
    mm.title,
    mm.year,
    mm.images,
    mt.to_state,
    mt.sort_key,
    mt.download_id,
    dc.id AS dc_id,
    dc.host AS dc_host,
    dc.port AS dc_port
FROM movie AS m
INNER JOIN movie_transition AS mt ON m.id = mt.movie_id AND mt.most_recent = 1
INNER JOIN movie_metadata AS mm ON m.movie_metadata_id = mm.id
LEFT JOIN download_client AS dc ON mt.download_client_id = dc.id
WHERE mt.to_state = 'downloading'
ORDER BY mt.sort_key DESC
`

type ListDownloadingMoviesRow struct {
	ID         int64
	TmdbID     int64
	Title      string
	Year       sql.NullInt64
	Images     string
	ToState    string
	SortKey    int64
	DownloadID sql.NullString
	DcID       sql.NullInt64
	DcHost     sql.NullString
	DcPort     sql.NullInt64
}

func (q *Queries) ListDownloadingMovies(ctx context.Context) ([]ListDownloadingMoviesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadingMovies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDownloadingMoviesRow
	for rows.Next() {
		var i ListDownloadingMoviesRow
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.Year,
			&i.Images,
			&i.ToState,
			&i.SortKey,
			&i.DownloadID,
			&i.DcID,
			&i.DcHost,
			&i.DcPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDownloadingSeries = `-- name: ListDownloadingSeries :many
SELECT
    se.id,
    sm.tmdb_id,
    sm.title,
    sm.poster_path,
    st.to_state,
    st.sort_key,
    st.download_id,
    se.season_number,
    dc.id AS dc_id,
    dc.host AS dc_host,
    dc.port AS dc_port
FROM season AS se
INNER JOIN
    season_transition AS st
    ON se.id = st.season_id AND st.most_recent = 1
INNER JOIN series AS ser ON se.series_id = ser.id
LEFT JOIN series_metadata AS sm ON ser.series_metadata_id = sm.id
LEFT JOIN download_client AS dc ON st.download_client_id = dc.id
WHERE st.to_state = 'downloading'
ORDER BY st.sort_key DESC
`

type ListDownloadingSeriesRow struct {
	ID           int64
	TmdbID       sql.NullInt64
	Title        sql.NullString
	PosterPath   sql.NullString
	ToState      string
	SortKey      int64
	DownloadID   sql.NullString
	SeasonNumber int64
	DcID         sql.NullInt64
	DcHost       sql.NullString
	DcPort       sql.NullInt64
}

func (q *Queries) ListDownloadingSeries(ctx context.Context) ([]ListDownloadingSeriesRow, error) {
	rows, err := q.db.QueryContext(ctx, listDownloadingSeries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListDownloadingSeriesRow
	for rows.Next() {
		var i ListDownloadingSeriesRow
		if err := rows.Scan(
			&i.ID,
			&i.TmdbID,
			&i.Title,
			&i.PosterPath,
			&i.ToState,
			&i.SortKey,
			&i.DownloadID,
			&i.SeasonNumber,
			&i.DcID,
			&i.DcHost,
			&i.DcPort,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listErrorJobs = `-- name: ListErrorJobs :many
SELECT
    j.id,
    j.type,
    jt.to_state,
    j.created_at,
    jt.updated_at
FROM job AS j
INNER JOIN job_transition AS jt ON j.id = jt.job_id AND jt.most_recent = 1
WHERE
    jt.to_state = 'error'
    AND jt.updated_at >= ?1
ORDER BY jt.updated_at DESC
`

type ListErrorJobsRow struct {
	ID        int64
	Type      string
	ToState   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListErrorJobs(ctx context.Context, cutoffDatetime sql.NullTime) ([]ListErrorJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listErrorJobs, cutoffDatetime)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListErrorJobsRow
	for rows.Next() {
		var i ListErrorJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ToState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRunningJobs = `-- name: ListRunningJobs :many
SELECT
    j.id,
    j.type,
    jt.to_state,
    j.created_at,
    jt.updated_at
FROM job AS j
INNER JOIN job_transition AS jt ON j.id = jt.job_id AND jt.most_recent = 1
WHERE jt.to_state = 'running'
ORDER BY j.created_at DESC
`

type ListRunningJobsRow struct {
	ID        int64
	Type      string
	ToState   string
	CreatedAt sql.NullTime
	UpdatedAt sql.NullTime
}

func (q *Queries) ListRunningJobs(ctx context.Context) ([]ListRunningJobsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRunningJobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRunningJobsRow
	for rows.Next() {
		var i ListRunningJobsRow
		if err := rows.Scan(
			&i.ID,
			&i.Type,
			&i.ToState,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
