// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"database/sql"
	"time"
)

type DownloadClient struct {
	ID             int64
	Type           string
	Implementation string
	Scheme         string
	Host           string
	Port           int64
	ApiKey         sql.NullString
}

type Episode struct {
	ID                int64
	SeasonID          int64
	EpisodeNumber     int64
	Monitored         int64
	EpisodeMetadataID sql.NullInt64
	EpisodeFileID     sql.NullInt64
}

type EpisodeFile struct {
	ID               int64
	Quality          string
	Size             int64
	Added            time.Time
	RelativePath     sql.NullString
	OriginalFilePath sql.NullString
}

type EpisodeMetadatum struct {
	ID               int64
	SeasonMetadataID int64
	Number           int64
	TmdbID           int64
	Title            string
	Overview         sql.NullString
	AirDate          sql.NullTime
	Runtime          sql.NullInt64
	StillPath        sql.NullString
}

type EpisodeTransition struct {
	ID                     int64
	EpisodeID              int64
	ToState                string
	FromState              sql.NullString
	MostRecent             bool
	SortKey                int64
	DownloadClientID       sql.NullInt64
	DownloadID             sql.NullString
	IsEntireSeasonDownload sql.NullBool
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
}

type Indexer struct {
	ID       int64
	Name     string
	Priority int64
	Uri      string
	ApiKey   sql.NullString
}

type Job struct {
	ID        int64
	Type      string
	CreatedAt sql.NullTime
}

type JobTransition struct {
	ID         int64
	JobID      int64
	Type       string
	ToState    string
	FromState  sql.NullString
	MostRecent bool
	SortKey    int64
	Error      sql.NullString
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}

type Movie struct {
	ID                  int64
	Path                sql.NullString
	Monitored           int64
	QualityProfileID    int64
	Added               sql.NullTime
	Tags                sql.NullString
	AddOptions          sql.NullString
	MovieFileID         sql.NullInt64
	MinimumAvailability int64
	MovieMetadataID     sql.NullInt64
	LastSearchTime      sql.NullTime
}

type MovieFile struct {
	ID               int64
	Quality          string
	Size             int64
	DateAdded        time.Time
	SceneName        sql.NullString
	MediaInfo        sql.NullString
	ReleaseGroup     sql.NullString
	RelativePath     sql.NullString
	Edition          sql.NullString
	Languages        string
	IndexerFlags     int64
	OriginalFilePath sql.NullString
}

type MovieMetadatum struct {
	ID                 int64
	TmdbID             int64
	ImdbID             sql.NullString
	Images             string
	Genres             sql.NullString
	Title              string
	SortTitle          sql.NullString
	CleanTitle         sql.NullString
	OriginalTitle      sql.NullString
	CleanOriginalTitle sql.NullString
	OriginalLanguage   int64
	Status             int64
	LastInfoSync       sql.NullTime
	Runtime            int64
	InCinemas          sql.NullTime
	ReleaseDate        sql.NullTime
	Year               sql.NullInt64
	SecondaryYear      sql.NullInt64
	Ratings            sql.NullString
	Recommendations    string
	Certification      sql.NullString
	YoutubeTrailerID   sql.NullString
	Studio             sql.NullString
	Overview           sql.NullString
	Website            sql.NullString
	Popularity         sql.NullFloat64
	CollectionTmdbID   sql.NullInt64
	CollectionTitle    sql.NullString
}

type MovieTransition struct {
	ID               int64
	MovieID          int64
	ToState          string
	FromState        sql.NullString
	MostRecent       bool
	SortKey          int64
	DownloadClientID sql.NullInt64
	DownloadID       sql.NullString
	CreatedAt        sql.NullTime
	UpdatedAt        sql.NullTime
}

type QualityDefinition struct {
	ID            int64
	QualityID     int64
	Name          string
	PreferredSize float64
	MinSize       float64
	MaxSize       float64
	MediaType     string
}

type QualityProfile struct {
	ID              int64
	Name            string
	CutoffQualityID sql.NullInt64
	UpgradeAllowed  bool
}

type QualityProfileItem struct {
	ID        int64
	ProfileID int64
	QualityID int64
}

type Season struct {
	ID               int64
	SeriesID         int64
	SeasonNumber     int64
	SeasonMetadataID sql.NullInt64
	Monitored        int64
}

type SeasonMetadatum struct {
	ID               int64
	SeriesMetadataID int64
	Number           int64
	TmdbID           int64
	Title            string
	Overview         sql.NullString
	AirDate          sql.NullTime
}

type SeasonTransition struct {
	ID                     int64
	SeasonID               int64
	ToState                string
	FromState              sql.NullString
	MostRecent             bool
	SortKey                int64
	DownloadClientID       sql.NullInt64
	DownloadID             sql.NullString
	IsEntireSeasonDownload sql.NullBool
	CreatedAt              sql.NullTime
	UpdatedAt              sql.NullTime
}

type Series struct {
	ID                int64
	Path              sql.NullString
	Monitored         int64
	Added             sql.NullTime
	QualityProfileID  int64
	SeriesMetadataID  sql.NullInt64
	LastSearchTime    sql.NullTime
	MonitorNewSeasons int64
}

type SeriesMetadatum struct {
	ID             int64
	TmdbID         int64
	Title          string
	Overview       sql.NullString
	LastInfoSync   sql.NullTime
	FirstAirDate   sql.NullTime
	LastAirDate    sql.NullTime
	SeasonCount    int64
	EpisodeCount   int64
	Status         string
	PosterPath     sql.NullString
	ExternalIds    sql.NullString
	WatchProviders sql.NullString
}

type SeriesTransition struct {
	ID         int64
	SeriesID   int64
	ToState    string
	FromState  sql.NullString
	MostRecent bool
	SortKey    int64
	CreatedAt  sql.NullTime
	UpdatedAt  sql.NullTime
}
