// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	GetLibraryStatsByState(ctx context.Context) ([]GetLibraryStatsByStateRow, error)
}

var _ Querier = (*Queries)(nil)
