// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlcdb

import (
	"context"
)

type Querier interface {
	GetMovieStatsByState(ctx context.Context) ([]GetMovieStatsByStateRow, error)
	GetTVStatsByState(ctx context.Context) ([]GetTVStatsByStateRow, error)
}

var _ Querier = (*Queries)(nil)
