// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcdb

import (
	"context"
	"database/sql"
)

type Querier interface {
	CountTransitionsByDate(ctx context.Context, arg CountTransitionsByDateParams) (int64, error)
	GetEntityTransitionsEpisode(ctx context.Context, id int64) ([]GetEntityTransitionsEpisodeRow, error)
	GetEntityTransitionsJob(ctx context.Context, id int64) ([]GetEntityTransitionsJobRow, error)
	GetEntityTransitionsMovie(ctx context.Context, id int64) ([]GetEntityTransitionsMovieRow, error)
	GetEntityTransitionsSeason(ctx context.Context, id int64) ([]GetEntityTransitionsSeasonRow, error)
	GetEntityTransitionsSeries(ctx context.Context, id int64) ([]GetEntityTransitionsSeriesRow, error)
	GetEpisodeTransitionItems(ctx context.Context, arg GetEpisodeTransitionItemsParams) ([]GetEpisodeTransitionItemsRow, error)
	GetEpisodeTransitionItemsNoLimit(ctx context.Context, arg GetEpisodeTransitionItemsNoLimitParams) ([]GetEpisodeTransitionItemsNoLimitRow, error)
	GetJobTransitionItems(ctx context.Context, arg GetJobTransitionItemsParams) ([]GetJobTransitionItemsRow, error)
	GetJobTransitionItemsNoLimit(ctx context.Context, arg GetJobTransitionItemsNoLimitParams) ([]GetJobTransitionItemsNoLimitRow, error)
	GetJobTransitionsByDate(ctx context.Context, arg GetJobTransitionsByDateParams) ([]GetJobTransitionsByDateRow, error)
	GetLibraryStatsByState(ctx context.Context) ([]GetLibraryStatsByStateRow, error)
	GetMovieTransitionItems(ctx context.Context, arg GetMovieTransitionItemsParams) ([]GetMovieTransitionItemsRow, error)
	GetMovieTransitionItemsNoLimit(ctx context.Context, arg GetMovieTransitionItemsNoLimitParams) ([]GetMovieTransitionItemsNoLimitRow, error)
	GetMovieTransitionsByDate(ctx context.Context, arg GetMovieTransitionsByDateParams) ([]GetMovieTransitionsByDateRow, error)
	GetSeasonTransitionItems(ctx context.Context, arg GetSeasonTransitionItemsParams) ([]GetSeasonTransitionItemsRow, error)
	GetSeasonTransitionItemsNoLimit(ctx context.Context, arg GetSeasonTransitionItemsNoLimitParams) ([]GetSeasonTransitionItemsNoLimitRow, error)
	GetSeriesTransitionsByDate(ctx context.Context, arg GetSeriesTransitionsByDateParams) ([]GetSeriesTransitionsByDateRow, error)
	ListDownloadingMovies(ctx context.Context) ([]ListDownloadingMoviesRow, error)
	ListDownloadingSeries(ctx context.Context) ([]ListDownloadingSeriesRow, error)
	ListErrorJobs(ctx context.Context, cutoffDatetime sql.NullTime) ([]ListErrorJobsRow, error)
	ListRunningJobs(ctx context.Context) ([]ListRunningJobsRow, error)
}

var _ Querier = (*Queries)(nil)
