// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: stats.sql

package sqlcdb

import (
	"context"
)

const getLibraryStatsByState = `-- name: GetLibraryStatsByState :many
SELECT 'movie' AS media_type,
       movie_transition.to_state AS state,
       COUNT(movie.id) AS count
FROM movie
INNER JOIN movie_transition ON (movie.id = movie_transition.movie_id AND movie_transition.most_recent = 1)
GROUP BY movie_transition.to_state
UNION ALL
SELECT 'series' AS media_type,
       series_transition.to_state AS state,
       COUNT(series.id) AS count
FROM series
INNER JOIN series_transition ON (series.id = series_transition.series_id AND series_transition.most_recent = 1)
GROUP BY series_transition.to_state
ORDER BY media_type, state
`

type GetLibraryStatsByStateRow struct {
	MediaType string
	State     string
	Count     int64
}

func (q *Queries) GetLibraryStatsByState(ctx context.Context) ([]GetLibraryStatsByStateRow, error) {
	rows, err := q.db.QueryContext(ctx, getLibraryStatsByState)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLibraryStatsByStateRow
	for rows.Next() {
		var i GetLibraryStatsByStateRow
		if err := rows.Scan(&i.MediaType, &i.State, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
