tmdb:
  host: my-host
  scheme: https
  apiKey: my-api-key
prowlarr:
  host: my-prowlarr-host
  scheme: https
  apiKey: my-prowlarr-api-key
manager:
  jobs:
    movieIndex: 15m
    movieReconcile: 10m
