//
// Code generated by go-jet DO NOT EDIT.
//
// WARNING: Changes to this file may cause incorrect behavior
// and will be lost if the code is regenerated
//

package table

import (
	"github.com/go-jet/jet/v2/sqlite"
)

var MovieMetadata = newMovieMetadataTable("", "MovieMetadata", "")

type movieMetadataTable struct {
	sqlite.Table

	// Columns
	ID                 sqlite.ColumnInteger
	TmdbId             sqlite.ColumnInteger
	ImdbId             sqlite.ColumnString
	Images             sqlite.ColumnString
	Genres             sqlite.ColumnString
	Title              sqlite.ColumnString
	SortTitle          sqlite.ColumnString
	CleanTitle         sqlite.ColumnString
	OriginalTitle      sqlite.ColumnString
	CleanOriginalTitle sqlite.ColumnString
	OriginalLanguage   sqlite.ColumnInteger
	Status             sqlite.ColumnInteger
	LastInfoSync       sqlite.ColumnTimestamp
	Runtime            sqlite.ColumnInteger
	InCinemas          sqlite.ColumnTimestamp
	PhysicalRelease    sqlite.ColumnTimestamp
	DigitalRelease     sqlite.ColumnTimestamp
	Year               sqlite.ColumnInteger
	SecondaryYear      sqlite.ColumnInteger
	Ratings            sqlite.ColumnString
	Recommendations    sqlite.ColumnString
	Certification      sqlite.ColumnString
	YouTubeTrailerId   sqlite.ColumnString
	Studio             sqlite.ColumnString
	Overview           sqlite.ColumnString
	Website            sqlite.ColumnString
	Popularity         sqlite.ColumnFloat
	CollectionTmdbId   sqlite.ColumnInteger
	CollectionTitle    sqlite.ColumnString

	AllColumns     sqlite.ColumnList
	MutableColumns sqlite.ColumnList
}

type MovieMetadataTable struct {
	movieMetadataTable

	EXCLUDED movieMetadataTable
}

// AS creates new MovieMetadataTable with assigned alias
func (a MovieMetadataTable) AS(alias string) *MovieMetadataTable {
	return newMovieMetadataTable(a.SchemaName(), a.TableName(), alias)
}

// Schema creates new MovieMetadataTable with assigned schema name
func (a MovieMetadataTable) FromSchema(schemaName string) *MovieMetadataTable {
	return newMovieMetadataTable(schemaName, a.TableName(), a.Alias())
}

// WithPrefix creates new MovieMetadataTable with assigned table prefix
func (a MovieMetadataTable) WithPrefix(prefix string) *MovieMetadataTable {
	return newMovieMetadataTable(a.SchemaName(), prefix+a.TableName(), a.TableName())
}

// WithSuffix creates new MovieMetadataTable with assigned table suffix
func (a MovieMetadataTable) WithSuffix(suffix string) *MovieMetadataTable {
	return newMovieMetadataTable(a.SchemaName(), a.TableName()+suffix, a.TableName())
}

func newMovieMetadataTable(schemaName, tableName, alias string) *MovieMetadataTable {
	return &MovieMetadataTable{
		movieMetadataTable: newMovieMetadataTableImpl(schemaName, tableName, alias),
		EXCLUDED:           newMovieMetadataTableImpl("", "excluded", ""),
	}
}

func newMovieMetadataTableImpl(schemaName, tableName, alias string) movieMetadataTable {
	var (
		IDColumn                 = sqlite.IntegerColumn("Id")
		TmdbIdColumn             = sqlite.IntegerColumn("TmdbId")
		ImdbIdColumn             = sqlite.StringColumn("ImdbId")
		ImagesColumn             = sqlite.StringColumn("Images")
		GenresColumn             = sqlite.StringColumn("Genres")
		TitleColumn              = sqlite.StringColumn("Title")
		SortTitleColumn          = sqlite.StringColumn("SortTitle")
		CleanTitleColumn         = sqlite.StringColumn("CleanTitle")
		OriginalTitleColumn      = sqlite.StringColumn("OriginalTitle")
		CleanOriginalTitleColumn = sqlite.StringColumn("CleanOriginalTitle")
		OriginalLanguageColumn   = sqlite.IntegerColumn("OriginalLanguage")
		StatusColumn             = sqlite.IntegerColumn("Status")
		LastInfoSyncColumn       = sqlite.TimestampColumn("LastInfoSync")
		RuntimeColumn            = sqlite.IntegerColumn("Runtime")
		InCinemasColumn          = sqlite.TimestampColumn("InCinemas")
		PhysicalReleaseColumn    = sqlite.TimestampColumn("PhysicalRelease")
		DigitalReleaseColumn     = sqlite.TimestampColumn("DigitalRelease")
		YearColumn               = sqlite.IntegerColumn("Year")
		SecondaryYearColumn      = sqlite.IntegerColumn("SecondaryYear")
		RatingsColumn            = sqlite.StringColumn("Ratings")
		RecommendationsColumn    = sqlite.StringColumn("Recommendations")
		CertificationColumn      = sqlite.StringColumn("Certification")
		YouTubeTrailerIdColumn   = sqlite.StringColumn("YouTubeTrailerId")
		StudioColumn             = sqlite.StringColumn("Studio")
		OverviewColumn           = sqlite.StringColumn("Overview")
		WebsiteColumn            = sqlite.StringColumn("Website")
		PopularityColumn         = sqlite.FloatColumn("Popularity")
		CollectionTmdbIdColumn   = sqlite.IntegerColumn("CollectionTmdbId")
		CollectionTitleColumn    = sqlite.StringColumn("CollectionTitle")
		allColumns               = sqlite.ColumnList{IDColumn, TmdbIdColumn, ImdbIdColumn, ImagesColumn, GenresColumn, TitleColumn, SortTitleColumn, CleanTitleColumn, OriginalTitleColumn, CleanOriginalTitleColumn, OriginalLanguageColumn, StatusColumn, LastInfoSyncColumn, RuntimeColumn, InCinemasColumn, PhysicalReleaseColumn, DigitalReleaseColumn, YearColumn, SecondaryYearColumn, RatingsColumn, RecommendationsColumn, CertificationColumn, YouTubeTrailerIdColumn, StudioColumn, OverviewColumn, WebsiteColumn, PopularityColumn, CollectionTmdbIdColumn, CollectionTitleColumn}
		mutableColumns           = sqlite.ColumnList{TmdbIdColumn, ImdbIdColumn, ImagesColumn, GenresColumn, TitleColumn, SortTitleColumn, CleanTitleColumn, OriginalTitleColumn, CleanOriginalTitleColumn, OriginalLanguageColumn, StatusColumn, LastInfoSyncColumn, RuntimeColumn, InCinemasColumn, PhysicalReleaseColumn, DigitalReleaseColumn, YearColumn, SecondaryYearColumn, RatingsColumn, RecommendationsColumn, CertificationColumn, YouTubeTrailerIdColumn, StudioColumn, OverviewColumn, WebsiteColumn, PopularityColumn, CollectionTmdbIdColumn, CollectionTitleColumn}
	)

	return movieMetadataTable{
		Table: sqlite.NewTable(schemaName, tableName, alias, allColumns...),

		//Columns
		ID:                 IDColumn,
		TmdbId:             TmdbIdColumn,
		ImdbId:             ImdbIdColumn,
		Images:             ImagesColumn,
		Genres:             GenresColumn,
		Title:              TitleColumn,
		SortTitle:          SortTitleColumn,
		CleanTitle:         CleanTitleColumn,
		OriginalTitle:      OriginalTitleColumn,
		CleanOriginalTitle: CleanOriginalTitleColumn,
		OriginalLanguage:   OriginalLanguageColumn,
		Status:             StatusColumn,
		LastInfoSync:       LastInfoSyncColumn,
		Runtime:            RuntimeColumn,
		InCinemas:          InCinemasColumn,
		PhysicalRelease:    PhysicalReleaseColumn,
		DigitalRelease:     DigitalReleaseColumn,
		Year:               YearColumn,
		SecondaryYear:      SecondaryYearColumn,
		Ratings:            RatingsColumn,
		Recommendations:    RecommendationsColumn,
		Certification:      CertificationColumn,
		YouTubeTrailerId:   YouTubeTrailerIdColumn,
		Studio:             StudioColumn,
		Overview:           OverviewColumn,
		Website:            WebsiteColumn,
		Popularity:         PopularityColumn,
		CollectionTmdbId:   CollectionTmdbIdColumn,
		CollectionTitle:    CollectionTitleColumn,

		AllColumns:     allColumns,
		MutableColumns: mutableColumns,
	}
}
